import { useEffect, useMemo, useState } from "react";
import { Music, Pencil, Plus, Trash2 } from "lucide-react";
import { Navigate } from "react-router-dom";
import { ADMIN_PASSWORD } from "../constants/admin";
import { isAdminSessionAuthenticated } from "../utils/adminSession";
import { createEmptyMusicBlock, createEmptyMusicMoment, createEmptyMusicSong, normalizeMusicBlocks, normalizeMusicMoments, normalizeMusicSongs, persistMusicSongs, validateMusicBlock, validateMusicMoment, validateMusicSong } from "../services/musicService";
import { discardAdminMusicChanges, getAdminDataSnapshot, getAdminMusicChangesSummary, loadAdminDataOnce, markAdminDataSaved, setAdminMusic, setAdminMusicBlocks, setAdminMusicMoments } from "../services/adminDataStore";
import { AdminPage, AdminPendingChangesActions, AdminTableSection, Card, EditorDialog, UnsavedChangesDialog } from "../components/admin/common";
import IconButton from "../components/ui/IconButton";
import DeleteDialog from "../components/ui/DeleteDialog";
import Spinner from "../components/ui/Spinner";
import useSpinner from "../hooks/useSpinner";
import useIsMobileView from "../hooks/useIsMobileView";
import useAdminLocalChanges from "../hooks/useAdminLocalChanges";

const header = { eyebrow: "Organización", title: "Escaleta musical", text: "Organiza momentos y canciones de vuestra boda." };
export default function AdminMusic() {
  const authenticated = isAdminSessionAuthenticated(); const spinner = useSpinner(); const mobile = useIsMobileView();
  const [loading, setLoading] = useState(true); const [music, setMusic] = useState([]); const [moments, setMoments] = useState([]); const [blocks, setBlocks] = useState([]); const [editing, setEditing] = useState(null); const [editingType, setEditingType] = useState(""); const [errors, setErrors] = useState({}); const [deleteTarget, setDeleteTarget] = useState(null);
  useEffect(() => { if (!authenticated) return; loadAdminDataOnce({ password: ADMIN_PASSWORD }).then((snapshot) => { setMusic(normalizeMusicSongs(snapshot.music)); setMoments(normalizeMusicMoments(snapshot.musicMoments)); setBlocks(normalizeMusicBlocks(snapshot.musicBlocks)); }).catch(console.error).finally(() => setLoading(false)); }, [authenticated]);
  const changes = getAdminMusicChangesSummary(); const pending = changes.length > 0;
  const apply = (nextMusic, nextMoments, nextBlocks = blocks) => { const songs = normalizeMusicSongs(nextMusic); const normalizedMoments = normalizeMusicMoments(nextMoments); const normalizedBlocks = normalizeMusicBlocks(nextBlocks); setMusic(songs); setMoments(normalizedMoments); setBlocks(normalizedBlocks); setAdminMusic(songs); setAdminMusicMoments(normalizedMoments); setAdminMusicBlocks(normalizedBlocks); };
  const save = async () => { if (!pending) return true; try { spinner.show("Guardando escaleta musical..."); const saved = await persistMusicSongs({ password: ADMIN_PASSWORD, music, moments, blocks }); apply(saved.music, saved.moments, saved.blocks); markAdminDataSaved({ music: saved.music, musicMoments: saved.moments, musicBlocks: saved.blocks }); return true; } catch (error) { console.error(error); return false; } finally { spinner.hide(); } };
  const discard = () => { const restored = discardAdminMusicChanges(); setMusic(restored); const snapshot = getAdminDataSnapshot(); setMoments(normalizeMusicMoments(snapshot.musicMoments)); setBlocks(normalizeMusicBlocks(snapshot.musicBlocks)); setEditing(null); setDeleteTarget(null); };
  const submit = (event) => { event.preventDefault(); const validation = editingType === "moment" ? validateMusicMoment(editing) : editingType === "block" ? validateMusicBlock(editing) : validateMusicSong(editing); setErrors(validation); if (Object.keys(validation).length) return; if (editingType === "moment") apply(music, [...moments.filter((item) => item.id !== editing.id), editing]); else if (editingType === "block") apply(music, moments, [...blocks.filter((item) => item.id !== editing.id), editing]); else apply([...music.filter((item) => item.id !== editing.id), editing], moments); setEditing(null); };
  const confirmDelete = () => { if (deleteTarget.type === "moment") apply(music.filter((song) => song.momentId !== deleteTarget.item.id), moments.filter((moment) => moment.id !== deleteTarget.item.id), blocks.filter((block) => block.momentId !== deleteTarget.item.id)); else if (deleteTarget.type === "block") apply(music, moments, blocks.filter((block) => block.id !== deleteTarget.item.id)); else apply(music.filter((song) => song.id !== deleteTarget.item.id), moments); setDeleteTarget(null); };
  const { blocker, cancelBlockedNavigation, discardAndContinueNavigation, saveAndContinueNavigation } = useAdminLocalChanges({ hasPendingChanges: pending, onDiscard: discard, onSave: save });
  const grouped = useMemo(() => moments.map((moment) => ({ moment, songs: music.filter((song) => song.momentId === moment.id), blocks: blocks.filter((block) => block.momentId === moment.id) })), [music, moments, blocks]);
  if (!authenticated) return <Navigate to="/admin" replace />;
  return <AdminPage header={header} innerClassName="max-w-7xl py-6">{() => <>
    {spinner.loading && <Spinner text={spinner.text} />}
    <AdminPendingChangesActions changes={changes} hasPendingChanges={pending} loading={loading} onDiscard={discard} onSave={save} saving={spinner.loading} showText={!mobile} />
    <AdminTableSection className="mt-4" loading={loading} eyebrow="Escaleta musical" title="Momentos de la boda" count={`${music.length} canciones`} actions={<MusicActions onMoment={() => { setEditingType("moment"); setEditing(createEmptyMusicMoment()); setErrors({}); }} />} actionsFullWidth headerActions={<MusicActions compact onMoment={() => { setEditingType("moment"); setEditing(createEmptyMusicMoment()); setErrors({}); }} />}>
      <div className="grid gap-4 md:grid-cols-2">{grouped.map(({ moment, songs, blocks: momentBlocks }) => <Card key={moment.id} actionsPlacement="overlay" actions={<MomentCardActions onDelete={() => setDeleteTarget({ type: "moment", item: moment })} onEdit={() => { setEditingType("moment"); setEditing(moment); setErrors({}); }}/>} eyebrow={moment.description} title={moment.label}><div className="mt-4 space-y-2">{momentBlocks.map((block) => <div key={block.id} className="flex items-center gap-2 rounded-xl border border-[var(--color-border-strong)] bg-[var(--color-bg-soft)]/50 px-3 py-2"><button className="min-w-0 flex-1 text-left" onClick={() => { setEditingType("block"); setEditing(block); setErrors({}); }} type="button"><b className="block truncate text-sm">{block.name}</b><span className="block truncate text-xs text-[var(--color-muted)]">{block.style} · {block.duration}</span></button><IconButton icon={<Trash2 size={15}/>} label="Eliminar bloque" tone="danger" onClick={() => setDeleteTarget({ type: "block", item: block })}/></div>)}{songs.map((song) => <div key={song.id} className="flex items-center gap-2 rounded-xl border border-[var(--color-border)] bg-white/70 px-3 py-2"><button className="min-w-0 flex-1 text-left" onClick={() => { setEditingType("song"); setEditing(song); setErrors({}); }} type="button"><b className="block truncate text-sm">{song.title}</b><span className="block truncate text-xs text-[var(--color-muted)]">{song.name}{song.notes ? ` · ${song.notes}` : ""}</span></button><IconButton icon={<Trash2 size={15}/>} label="Eliminar canción" tone="danger" onClick={() => setDeleteTarget({ type: "song", item: song })}/></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2"><IconButton icon={<Music size={16}/>} label="Añadir canción" showText="always" onClick={() => { setEditingType("song"); setEditing(createEmptyMusicSong({ momentId: moment.id })); setErrors({}); }}>Añadir canción</IconButton><IconButton icon={<Plus size={16}/>} label="Añadir bloque" showText="always" tone="terciary" onClick={() => { setEditingType("block"); setEditing(createEmptyMusicBlock({ momentId: moment.id })); setErrors({}); }}>Añadir bloque</IconButton></div></Card>)}</div>
    </AdminTableSection>
    {editing && <EditorDialog title={editingType === "moment" ? "Momento musical" : editingType === "block" ? "Bloque musical" : "Canción"} onClose={() => setEditing(null)}>{editingType === "moment" ? <MomentForm form={editing} errors={errors} onChange={(field, value) => setEditing({ ...editing, [field]: value })} onSubmit={submit}/> : editingType === "block" ? <BlockForm form={editing} errors={errors} onChange={(field, value) => setEditing({ ...editing, [field]: value })} onSubmit={submit}/> : <SongForm form={editing} errors={errors} onChange={(field, value) => setEditing({ ...editing, [field]: value })} onSubmit={submit}/>}</EditorDialog>}
    {deleteTarget && <DeleteDialog title={`Eliminar ${deleteTarget.type === "moment" ? "momento" : "canción"}`} message={deleteTarget.type === "moment" ? "También se eliminarán sus canciones asociadas." : "Esta canción se eliminará de la escaleta musical."} onCancel={() => setDeleteTarget(null)} onConfirm={confirmDelete}/>} {blocker.state === "blocked" && <UnsavedChangesDialog changes={changes} labels={{ eyebrow: "Cambios pendientes", exitWithoutSaving: "Salir sin guardar", keepEditing: "Seguir editando", saveAndExit: "Guardar y salir", text: "Hay cambios en la escaleta musical que todavía no se han guardado.", title: "¿Guardar cambios?" }} onCancel={cancelBlockedNavigation} onConfirm={discardAndContinueNavigation} onSaveAndExit={saveAndContinueNavigation}/>}</>}</AdminPage>;
}
function MusicActions({ compact, onMoment }) { return <div className={compact ? "flex gap-2" : "grid w-full gap-3"}><IconButton className={compact ? "h-10 w-10 !px-0" : "w-full"} icon={<Plus size={16}/>} label="Añadir momento" onClick={onMoment} showText={compact ? false : "always"}>Añadir momento</IconButton></div>; }
function MomentCardActions({ onDelete, onEdit }) { return <div className="grid shrink-0 grid-cols-2 gap-2 self-start"><IconButton className="h-10 w-10 !px-0" icon={<Trash2 size={16} strokeWidth={1.8}/>} label="Eliminar momento" onClick={onDelete} tone="danger"/><IconButton className="h-10 w-10 !px-0" icon={<Pencil size={16} strokeWidth={1.8}/>} label="Editar momento" onClick={onEdit} tone="primary"/></div>; }
function MomentForm({ form, errors, onChange, onSubmit }) { return <form className="mt-5 space-y-4" onSubmit={onSubmit}><Field label="Nombre del momento" value={form.label} error={errors.label} onChange={(value) => onChange("label", value)}/><Field label="Descripción" value={form.description} onChange={(value) => onChange("description", value)}/><Submit/></form>; }
function SongForm({ form, errors, onChange, onSubmit }) { return <form className="mt-5 space-y-4" onSubmit={onSubmit}><Field label="Nombre / intérprete" value={form.name} error={errors.name} onChange={(value) => onChange("name", value)}/><Field label="Título" value={form.title} error={errors.title} onChange={(value) => onChange("title", value)}/><Field label="Notas" value={form.notes} onChange={(value) => onChange("notes", value)}/><Submit/></form>; }
function BlockForm({ form, errors, onChange, onSubmit }) { return <form className="mt-5 space-y-4" onSubmit={onSubmit}><Field label="Nombre" value={form.name} error={errors.name} onChange={(value) => onChange("name", value)}/><Field label="Estilo de música" value={form.style} error={errors.style} onChange={(value) => onChange("style", value)}/><Field label="Tiempo total" value={form.duration} error={errors.duration} onChange={(value) => onChange("duration", value)}/><Submit/></form>; }
function Field({ label, value, error, onChange }) { return <label className="block text-sm">{label}<input className="mt-1 w-full rounded-xl border border-[var(--color-border)] bg-white p-3" value={value || ""} onChange={(event) => onChange(event.target.value)}/>{error && <span className="text-xs text-red-500">{error}</span>}</label>; }
function Submit() { return <IconButton icon={<Pencil size={16}/>} label="Guardar cambios" showText="always" type="submit">Guardar cambios</IconButton>; }
